# Generated by Django 4.1.4 on 2022-12-08 23:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('document', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(999999999999), django.core.validators.MinValueValidator(999999)])),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField()),
                ('modified_date', models.DateField()),
                ('bill_date', models.DateField()),
                ('price', models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(100)])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billinghub.client')),
            ],
        ),
    ]
