# Generated by Django 4.1.4 on 2022-12-15 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billinghub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='price',
            field=models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(-999999)]),
        ),
        migrations.AlterField(
            model_name='client',
            name='document',
            field=models.IntegerField(default=1, unique=True, validators=[django.core.validators.MaxValueValidator(999999999999), django.core.validators.MinValueValidator(999999)]),
        ),
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together={('bill_date', 'price', 'client')},
        ),
    ]
